### ISSUE TITLE
empty list of solutions

### ISSUE THREAD

**Issue by mgarriga** [aderenzis/cbr4SSPlatform#2]
After the memory optimizations in commit 7e83d69dd7e5331cf27c9aa7b91ba5a4ba607035, when running with swagger-based services, it raises an exception as follows:

```
TimesTags - nytimes.com-times_tags-1.0.0-swagger.json failed, exception java.util.NoSuchElementException: List is empty..
java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:45)
	at kotlin.collections.EmptyList.get(Collections.kt:33)
	at selection.SelectionKt.knn(Selection.kt:32)
	at selection.SelectionKt.findSolution(Selection.kt:57)
	at cbr.CBRKt.main(CBR.kt:85)
```

**Comment by rapkyt** [comment]
Thanks for your report, this issue has been already fixed in commit  516aa324d0fb1290b1fb360ac99c94fb418c203b.

Please update your local branch and reopen this ticket if necessary.
